#!/usr/bin/env bash

VIM="/Applications/MacVim.app/Contents/MacOS/Vim -v"

$VIM -u NONE -U NONE -N                      \
  --cmd 'set rtp+=../'                       \
  --cmd 'source ../plugin/localorie.vim' \
  -S runner.vim                              \
  test_*.vim                                 \
  $*

cat messages.log

grep -q "0 errors, 0 failures" messages.log
status=$?
rm messages.log
exit $status

